name: Lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@56ae093b028011bb536e45d6f8d46b45c4248489 # main

  prettier:
    name: Prettier
    uses: harryzcy/github-actions/.github/workflows/prettier.yml@56ae093b028011bb536e45d6f8d46b45c4248489 # main
