name: Lint

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@13a4c40f9699ea2915746978b58bb42160f771b6 # main

  prettier:
    name: Prettier
    uses: harryzcy/github-actions/.github/workflows/prettier.yml@13a4c40f9699ea2915746978b58bb42160f771b6 # main
