name: Release Drafter

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update:
    name: Generate Notes
    permissions:
      contents: write
      pull-requests: write
    uses: harryzcy/github-actions/.github/workflows/release-drafter.yml@2b6b19fc1e4fa82e5ed7be70baeb27e2526f1a07 # main
