name: Release Drafter

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update:
    name: Generate Notes
    permissions:
      contents: write
      pull-requests: write
    uses: harryzcy/github-actions/.github/workflows/release-drafter.yml@2d3c3315851099b16dcf3d6488dc56c164b0760e # main
