name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    name: GitHub
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: write
    uses: harryzcy/github-actions/.github/workflows/release.yml@5eaf925875721488eed093142fde35b53b8e6865 # main
