name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    name: GitHub
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: write
    uses: harryzcy/github-actions/.github/workflows/release.yml@25d834bc6f100ee46b88756cb6ec46204f04705a # main
