name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    name: GitHub
    if: github.repository_owner == 'harryzcy'
    permissions:
      contents: write
    uses: harryzcy/github-actions/.github/workflows/release.yml@2b18cd8e46647c70be37720c3d268811b62b8045 # main
