name: Release Drafter

on:
  push:
    branches:
      - main
    tags-ignore:
      - 'v*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  update:
    name: Generate Notes
    permissions:
      contents: write
      pull-requests: write
    uses: harryzcy/github-actions/.github/workflows/release-drafter.yml@5b9a56eb502247490f40d4a5a0b77e46f01b9b42 # main
